### PR TITLE
Fixes #127 and Fixes #126 - Form validations & scrolling errors issue

### LINKED ISSUE #126: Error Message Does Not Scroll
If a user receives an error message that has multiple errors and the text that describes the errors takes up more than the visible screen space they are unable to scroll to view the rest of the error message.

### LINKED ISSUE #127: Eliminate Presence Validations for Development Fields without Presence Requirement Indicator in the UI
The new development UI does not have asterisks for some fields, including group quarters (gq_pop), but these fields are required and throw a presence validation error if the user fails to fill them out.

Check the test suite to see if the views are relying on the presence of this data.

### PR DESCRIPTION
**Pull request by allthesignals**
This fixes issues with scrolling by adding some CSS. 

It also adds the correct requirement indicators, and makes them conditional. Includes a bit of transition animation so it’s not so jarring (easy 5 min. addition).

### CODE REVIEW

**Comment by mzagaja** [comment]
I am confused by commit https://github.com/MAPC/massbuilds/pull/184/commits/e8c4e42de5f3cd4e448c1a5f20def5e6c924866b which references two commits which do not seem related to the final result? It claims to be a revert but does not appear to actually be so.

**Comment by mzagaja** [comment]
Attempting to run the app after checking out the branch throws the following error for me:

screen shot 2016-12-28 at 3 32 38 pm

I am unsure what the appropriate path to surmounting this is. Is something supposed to be checked in? Do I need to run a bundle install or other command?

**Comment by allthesignals** [comment]
@mzagaja sorry, you have to re-run `npm install` and `bower install` in the `/searchapp` directory. This is done automatically in production. It's definitely akin to `bundle install`. Not sure if there's a pattern for having it done automatically? I can add a README note.

**Comment by mzagaja** [comment]
Thanks, I think that's just me not knowing about ember things. Maybe worth putting in a note that new installations require an npm install and bower install in the searchapp directory in README.

**Pull request merged**
