### PR TITLE
Ie11 fix

### PR DESCRIPTION
**Pull request by allthesignals**
This includes commits from #223.

This fixes compatibility issues with IE 11, tested manually over Browserstack on windows 10 and 11, IE 11, 10, addressing #218 by allowing the app to render correctly. 

Some changes were made to the Ember app's Rails layout template, so the development New and Search views should be tested extensively.

### CODE REVIEW

**Comment by mzagaja** [comment]
I QA'd this by testing both the search page and the new development page on my machine. It looks like things are pretty good to go. The one thing I'll note is (and I think it's an issue with the setup on my local machine) is my lack of dots. Then the other thing I noticed, which might not be related to your changes but looks like a mistake is the following field's gray text:

screen shot 2017-05-26 at 3 21 17 pm

**Comment by allthesignals** [comment]
@mzagaja Thanks! What do you mean by "your lack of dots"? Maybe open the browser console and paste the log. 

I think the field text is a separate issue and should be addressed in a separate PR.

**Comment by mzagaja** [comment]
The map points on the search map were not appearing for me when I did the filter. But my recollection is that has always occurred. I think if the gray text issue is another issue then I can approve this at this point.

**Comment by allthesignals** [comment]
@mzagaja is this deployed?

**Comment by allthesignals** [comment]
@mzagaja it needs to be merged into `master` first.

**Comment by mzagaja** [comment]
Do you want me to deploy to staging from develop before merging to master?

**Comment by allthesignals** [comment]
@mzagaja oh yes, forgot we had an actual staging server! Yes, then I can it run it through browserstack to make sure it solved the issue (it does locally).

**Comment by sannphilbrick** [comment]
@allthesignals @mzagaja is this ready to be deployed to the live site? It's still not showing up on my IE and I'm presenting to the Inner Core Committee on Wednesday. Since they're all municipal staff I think a lot of them will be using IE

**Pull request merged**
